version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker_files/Dockerfile
    volumes:
      - ./application:/app
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    depends_on:
      - db
  
  db:
    # https://hub.docker.com/_/postgres
    image: postgres:12.6
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
