version: '3'

services:
  db:
    image: postgres:13.2
    volumes:
      - db_data:/var/lib/mysql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - 15432:5432

volumes:
  db_data: